# Site settings
title: ret·ro·spec·tive
email: vitaliy.kolodenko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My look back and sometimes forward to some life events, interesting facts, thoughts and ideas.
  Primary areas of interest: Software Engineering, Mountain Biking, Travels, e.t.c. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  vitaliykolodenko

# Build settings
markdown: kramdown
